### ISSUE TITLE
How to do basic authentication for proxy?

### ISSUE THREAD

**Issue by OsKaR82** [mattsse/chromiumoxide#145]
Hello, I'm looking at several packages and this is the one I like the most for chrome, but I don't see the method for proxy authentication, any ideas?

**Comment by webhype** [comment]
There is none because Chrome has none. You need to run an instance of something like g3proxy on 127.0.0.1:31001 and *IT* has the proper username/password for your remote proxy configured in its .yaml file. Here's an example .yaml file:

```
server:
  - name: http1
    escaper: proxy_pp1
    type: http_proxy
    listen:
      address: "127.0.0.1:31001"
  - name: http2
    escaper: proxy_pp2
    type: http_proxy
    listen:
      address: "127.0.0.1:31002"
  - name: http0
    escaper: default
    type: http_proxy

# DNS resolver, you need to tell g3proxy where to resolve DNS names
resolver:
  - name: default
    type: c-ares
    server: 8.8.8.8

# See ~/mm/g3/g3proxy/doc/_build/configuration/escapers/index.html
escaper:
  - name: proxy_pp1
    type: proxy_http
    proxy_addr: "12.34.56.78:8080"
    proxy_username: "username1"
    proxy_password: "password1"
  - name: proxy_pp2
    type: proxy_http
    proxy_addr: "12.34.56.79:8080"
    proxy_username: "username2"
    proxy_password: "password2"
  - name: default
    type: direct_fixed
    resolver: default

log: stdout

```
